---
mgmt_gw: 172.20.1.1/28
mtu: 1500


#########################################
#####     DC Fabric Build           #####
#########################################
intf_id:
  leaf: 1
  spine: 0
  fw: 1
  gw: 1

bgp_as:
  leaf: 65100
  spine: 65200
  fw: 65300

loopback_ip:
  dc1-spine01: 20.100.1.1/32
  dc1-spine02: 20.100.1.2/32
  dc1-leaf01: 20.100.1.3/32
  dc1-leaf02: 20.100.1.4/32
  dc1-fw01: 20.100.1.5/32

intf_ip:
  dc1-spine01:
    - {intf: Ethernet1, prefix: 10.1.1.0/31, peer: dc1-leaf01, peer_intf: Ethernet9}
    - {intf: Ethernet2, prefix: 10.1.1.2/31, peer: dc1-leaf02, peer_intf: Ethernet9}
    - {intf: Ethernet6, prefix: 10.1.1.252/31, peer: dc1-spine02, peer_intf: Ethernet6}
    - {intf: Ethernet7, prefix: 10.1.3.0/31, peer: dc1-fw01, peer_intf: ge-0/0/1.0}
    - {intf: Ethernet9, prefix: 10.1.2.0/31, peer: vmx01, peer_intf: ge-0/0/2.0}
    - {intf: Ethernet8, prefix: 10.1.2.2/31, peer: vmx02, peer_intf: ge-0/0/2.0}

  dc1-spine02:
    - {intf: Ethernet1, prefix: 10.1.1.64/31, peer: dc1-leaf01, peer_intf: Ethernet8}
    - {intf: Ethernet2, prefix: 10.1.1.66/31, peer: dc1-leaf02, peer_intf: Ethernet8}
    - {intf: Ethernet6, prefix: 10.1.1.252/31, peer: dc1-spine01, peer_intf: Ethernet6}
    - {intf: Ethernet7, prefix: 10.1.3.64/31, peer: dc1-fw01, peer_intf: ge-0/0/2.0}
    - {intf: Ethernet9, prefix: 10.1.2.64/31, peer: vmx01, peer_intf: ge-0/0/3.0}
    - {intf: Ethernet8, prefix: 10.1.2.66/31, peer: vmx02, peer_intf: ge-0/0/3.0}

  dc1-leaf01:
    - {intf: Ethernet9, prefix: 10.1.1.0/31, peer: dc1-spine01, peer_intf: Ethernet1}
    - {intf: Ethernet8, prefix: 10.1.1.64/31, peer: dc1-spine02, peer_intf: Ethernet1}


  dc1-leaf02:
    - {intf: Ethernet9, prefix: 10.1.1.2/31, peer: dc1-spine01, peer_intf: Ethernet2}
    - {intf: Ethernet8, prefix: 10.1.1.66/31, peer: dc1-spine02, peer_intf: Ethernet2}


  dc1-fw01:
    - {intf: ge-0/0/1.0, prefix: 10.1.3.0/31, peer: dc1-spine01, peer_intf: Ethernet7}
    - {intf: ge-0/0/2.0, prefix: 10.1.3.64/31, peer: dc1-spine02, peer_intf: Ethernet7}

bgp_peers:
  dc1-spine01:
    - {peer: dc1-leaf01, local_as: 652001, peer_as: }
    - {peer: dc1-leaf01, local_as: 65001, peer_as: }
    - {peer: dc1-fw01, local_as: 65001, peer_as: }
    - {peer: vmx01, local_as: 65001, peer_as: }
    - {peer: vmx02, local_as: , peer_as: }
