---
# tasks file for eos_config
- name: Create Configuration for Arista Config
  block:
  - name: Create Directory to store Temp data
    file: name={{tmp_dir}} state=directory
    run_once: true  

  - name: Create Directory for each router
    file: name={{tmp_dir}}/{{inventory_hostname}} state=directory

  - name: Create Managment Configuration
    template:
        src: j2_eos_mgmt.j2
        dest: "{{tmp_dir}}/{{inventory_hostname}}/01_mgmt.cfg"

  - name: Create Interface Configuration
    template:
        src: j2_eos_intf.j2
        dest: "{{tmp_dir}}/{{inventory_hostname}}/02_intf.cfg"


  - name: Generate Final Device Configuration
    assemble:
        src: "{{tmp_dir}}/{{inventory_hostname}}"
        dest: "{{device_config}}/{{inventory_hostname}}.cfg"

  - name: Delete Temp Directory
    file: path={{tmp_dir}} state=absent
    run_once: true

  delegate_to: localhost
