---
- name: Deploy Config with Ansible and Git
  hosts: all
  tasks:
  - import_role: 
        name: create_git_branch

  - import_role: 
        name: deploy_config
    tags: [ deploy]
        
  - import_role: 
        name: git_branch_push
